version: "3.8"
services:
  app:
    container_name: app-neko
    build:
      args:
        user: neko
        uid: 1000
      context: ./docker/laravel
      dockerfile: Dockerfile
    working_dir: /var/www/code
    restart: unless-stopped
    volumes:
      - .:/var/www/code
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
    networks:
      - neko-network

  web:
    container_name: web-neko
    image: nginx
    restart: unless-stopped
    working_dir: /var/www/code
    user: root
    volumes:
      - .:/var/www/code
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4444:80
    networks:
      - neko-network

  database:
    container_name: postgres-neko
    image: postgres
    restart: unless-stopped
    volumes:
      - neko-database:/var/lib/postgres
#      - ./sourcefiles/postgres:/var/lib/postgresql/data
      - ./docker/postgres/database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: neko
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    networks:
      - neko-network

  database_price:
    container_name: timescale-neko-price
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    volumes:
      - neko-price-database:/var/lib/postgres
      #      - ./sourcefiles/postgres:/var/lib/postgresql/data
      - ./docker/postgres/databasePrice:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: neko
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 54321:5432
    networks:
      - neko-network

networks:
  neko-network:
    driver: bridge

volumes:
  neko-database:
    driver: local
  neko-price-database:
    driver: local
