version: "3.8"
services:
  app:
    container_name: app
    build:
      args:
        user: eduto
        uid: 1000
      context: ./docker/laravel
      dockerfile: Dockerfile
    working_dir: /var/www/code
    restart: unless-stopped
    volumes:
      - .:/var/www/code
    networks:
      - eduto-network

  web:
    container_name: web
    image: nginx
    restart: unless-stopped
    working_dir: /var/www/code
    user: root
    volumes:
      - .:/var/www/code
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - eduto-network

  database:
    container_name: mysql
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - eduto-database:/var/lib/mysql
      - ./docker/mysql/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - eduto-network

networks:
  eduto-network:
    driver: bridge

volumes:
  eduto-database:
    driver: local
